src/Entity/User.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 * fields ={"email"},
 * message="Email que vous avez rentré est déja utislisé !"
 * )
 *
 * 
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="8", minMessage ="Minimum 8 caracteres !")
     */
    private $password;

    /**
    *@Assert\EqualTo(propertyPath="password", message="Vous n'avez pas tapé le même mot de passe !")
    */
    public $confirm_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\Column(type="array")
     */
    private $roles ;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ville", cascade={"persist"})
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Villes", inversedBy="users")
     */
    private $city;

  

    public function getId()
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getRoles() {
        if (empty($this->roles)) {
        return ['ROLE_USER'];
        }
        return $this->roles;
    }

    public function setRoles($roles)
    {
        $this->roles[] = $roles;

        return $this;
    
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function eraseCredentials(){}

        public function getSalt(){}
    
        public function getCity(): ?Villes
        {
            return $this->city;
        }
    
        public function setCity(?Villes $city): self
        {
            $this->city = $city;
    
            return $this;
        }

}

src/Controller/HomeFoodtruckController.php
<?php

namespace App\Controller;

use App\Entity\User;


use App\Entity\Ville;
use App\Form\UserType;
use App\Form\ClientType;

use App\Repository\UserRepository;
use App\Repository\VilleRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class HomeFoodtruckController extends Controller
{
    /**
     * 
     * @Route("/foodtruck", name="home_foodtruck")
     * 
     * 
     */
    public function index(ObjectManager $manager, Request $request, VilleRepository $repo, UserRepository $userRepo)
    {
       

        return $this->render('home_foodtruck/accueil.html.twig', [
            
        ]);
    }
    /**
     * 
     * @Route("/search", name="search")
     * 
     * 
     */
    public function search(ObjectManager $manager, Request $request, VilleRepository $repo, UserRepository $userRepo)
    {
        if($request->query->get('ville')){
            $search = $request->query->get('ville');
        /* dump($search); */
       
            $resultat = $repo->findBy([
                'nom' => $search 
                ]);
               
                 /* dump($resultat); */
               
                foreach ($resultat as $key=>$value) {
                    
                    $idUser[] = $value->getId();
                     dump($idUser );
                     $foods = $userRepo->findByVille(
                     $idUser);
                 } 
                 if (empty($foods) ){
                    return $this->render('foodtruck/search.html.twig', [
                        'search' => 'null'

                    ]); 
                 }
                 dump($foods );
                
                 /* dump($idUse); */
             
                
          
                 return $this->render('foodtruck/search.html.twig', [
                        'search' => $foods

                    ]); 
        }
    } 

        /**
        * 
        * @Route("/foodtruck/profil/{id}", name="foodtruck_profil")
        */
        public function profil(User $user,Request $request) {

            $form = $this->createForm(ClientType::class, $user );
            $form->handleRequest($request);
            return $this->render('home_foodtruck/profil.html.twig',[
                'form_foodtruck' => $form->createView(),
                'user' => $user
            ]);
        }

       
    }
   /*  public function jquery(){
 
       
        $bdd = $this->getDoctrine()->getRepository('VillesRepository');
        $log = $_POST['birds'];
        
         
        $requete = $bdd->prepare('SELECT ville_nom ,ville_code_postal FROM villes WHERE ville_nom LIKE :log LIMIT 0,10'); // j'effectue ma requête SQL grâce au mot-clé LIKE
        $requete->execute(array('log' => $log."%"));
         
        $array = array(); // on créé le tableau
         
        while($donnee = $requete->fetch()) // on effectue une boucle pour obtenir les données
        {
            array_push($array, $donnee['ville_nom'] . ' '.$donnee['ville_code_postal']); // et on ajoute celles-ci à notre tableau
        }
    //    header('Content-Type: application/json');
        echo json_encode($array); // il n'y a plus qu'à convertir en JSON
        
    
    
       } */
   

templates/home_foodtruck/accueil.html.twig
{% extends '/home_foodtruck/index.html.twig' %}

{% block body %}
<div class="container" id="accueil" >
    <div class="jumbotron" id="accueilClient">
    <h1 class="display-3">Quoi manger ce soir ? </h1>
    <p class="lead">Trouvez votre foodtruck près de chez vous et commandez en ligne.</p>
    <hr class="my-4">
    <p>Une simple inscription ,gratuite, vous aurez la possibilité de commander en 
    ligne et de découvrir de nouvelle saveur innatendu .</p>
    <p class="lead">
        <a class="btn btn-success btn-lg" href="{{ path('client_food') }}" role="button">Nouveau client</a>
    </p>
    </div>

    <div class="jumbotron" id="accueilFood">
    <h1 class="display-3">Vous avez un foodtruck ?</h1>
    <p class="lead">Devenez visible grace a notre réseau !</p>
    <hr class="my-4">
    <p>Profitez de notre visibilité pour faire découvrir vos menus,
     vos positions géographiques et notre système de commande en ligne 
     ainsi qu'un espace de gestion en ligne de vos commandes.</p>
    <p class="lead">
        <a class="btn btn-success btn-lg" href="{{ path('foodtruckRegistre') }}" role="button">Nouveau foodtruck</a>
    </p>
    </div>
</div>
{% endblock  %}

{% block javascripts %}
<script src="/jquery.js"></script>
{% endblock %}

templates/home_foodtruck/index.html.twig
{# {% extends 'base.html.twig' %} #}


     <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Hanalei+Fill" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href=" /foodtruck.css " />
    
     {% block stylesheets %}{% endblock %}
        
    <body>
                <nav class="navbar navbar-expand-lg " >
                   <div class="collapse navbar-collapse" id="navbarColor02"> 
                        <ul class="nav nav-pills" role="menu" aria-labelledby="dLabel"  id="menu">
                       
                            <li><a href="/foodtruck" class="active">Accueil</a></li>
                           
                             <ul class="nav nav-pills" role="menu" aria-labelledby="dLabel"  id="menu">
                             
                                {% if not app.user or app.user.Roles['0'] == ['ROLE_CLIENT']  %}
                                <li><a href="{{ path('client_food') }}" class="active">Espace Client</a></li>
                                {% endif %}
                                 {% if not app.user or app.user.Roles['0'] == ['ROLE_FOODTRUCK']  %}
                                <li><a href="{{ path('foodtruckRegistre') }}" class="active">Espace Foodtruck</a></li>
                                 {% endif %}
                                <li><a href="{{ path('foodtrucks') }}" class="active">Nos Foodtruck</a></li>
                               
                                {% if not app.user %}
                                <li><a href="{{ path('login') }}">Connexion</a></li>
                                {% else %}
                                <li><a href="{{ path('logout') }}" class="active">Deconnexion</a></li> 
                                {% endif %}
                           {#  <?php 
                            } ?>

                            <?php if(isset($_SESSION['id']))
                            { ?>
                                <li><a href="/deconnexion">Deconnexion</a></li>
                            <?php
                            } ?>

                            <?php if (isset($_SESSION['idC']))
                            { ?>
                                <li><a href="/espace-client/profil">Mon Profil</a></li>
                                <li><a href="/tous-les-foodtrucks">Nos Foodtrucks</a></li>
                            <?php
                            } ?>

                            <?php if (isset($_SESSION['idF']))
                            { ?>
                                    
                                <li><a href="/espace-foodtruck/profil">Mon Profil</a></li>
                                <li><a href="/carte">Carte</a></li>
                                <li><a href="/espace-foodtruck/evenement">Evenement</a></li>
                                <li><a href="/espace-foodtruck/messages/<?php echo $_SESSION['id'];?>">Mes messages</a></li>
                            <?php
                            } ?>
                            <?php if (isset($_SESSION['id_pro']))
                            { ?>
                                <li><a href="/deconnexion">Deconnexion</a></li>
                                <li><a href="/espace-pros/profile">Mon Profil</a></li>
                            <?php
                            } ?>

                            <?php if (isset($_SESSION['id_admin']))
                            {?>
                                <li><a href="/deconnexion">Deconnexion</a></li>
                                <li><a href="/espace-administration">Administration</a></li>
                            <?php
                            } ?> #} 


                       {#  <?php if (isset($_SESSION['pseudo']) == true) { ?> 
                             <p id="messageHeader">
                                 <a href="/espace-client/messages/<?php echo $_SESSION['id'];?>">Mes messages</a>
                            </p>
                            <img src="/images/blankuser.png" id="visiteur" style="width: 40px; height: 50px;">

                            <div id="bonjour"><p>Bonjour <?php echo ' ' . $_SESSION['pseudo']; ?></p></div><br><br>
                           
                               
                        <?php } ?>
                        <?php if (isset($_SESSION['idF']) == true) { ?> 
                            <img src="/images/blankuser.png" id="visiteurFood" style="width: 40px; height: 50px;">

                            <div id="bonjourFood"><p>Bonjour <br><?php echo ' ' . $_SESSION['nom'] . ' ' . $_SESSION['prenom']; ?></div></p>
    
                        <?php } ?>

                        <?php if (isset($_SESSION['id_pro']) == true) { ?> 
                            <img src="/images/blankuser.png" id="visiteurFood" style="width: 40px; height: 50px;">

                            <div id="bonjourFood"><p>Bonjour <br><?php echo ' ' . $_SESSION['nom'] . ' ' . $_SESSION['prenom']; ?></div></p>

                        <?php } ?>
                        
 #}




                        </ul>
                    </div>
                </nav>  
                <div class="ui-widget" id="rechercheAccueil">
                    <form class="form-inline my-2 my-lg-0" id="searchVille" action='{{ path('search') }}'>
                        <input class="form-control mr-sm-2" type="text" id="searchVille" name='ville' placeholder="Rechercher par ville....">
                            <button class="btn btn-success my-2 my-sm-0" type="submit" id="boutonSearch">Trouver</button>
                    </form>
                </div> 
                    {% if app.user %}
                    <div id='profil' class="card text-white bg-secondary mb-3" style="max-width: 24rem;">
                            <div class="card-header">Bonjour {{ app.user.username }} </div>
                                <div class="card-body">
                                    <h4 class="card-title"></h4>
                                    <p class="card-text"><a href="{{ path('foodtruck_profil', { 'id' : app.user.id })  }}" id='lienProfil'>Votre profil</a></p>
                            </div>
                    </div>  
                    {% endif %}               
                    <div class="container">
                        <img src="/Pictures/foodtruck/banniere.png" alt="banniere" id="banniere"> 
                        
    {#  {{ dump(ville)}}  #} 
                   
                    </div>
                {#  <div class="ui-widget">  
            <label for="birds">Votre ville: </label>
            <input type="text" id="pro" name="ville" class='form-control'>
           
        </div> #}
    </body>
{% block body %}{% endblock %}








<script src='https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js'></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

{% block javascripts %}{% endblock %}

templates/home_foodtruck/login.html.twig
{% extends '/home_foodtruck/index.html.twig' %}

{% block body %}
<div class="form-group row" id="cadreForm">
<h1 class="titreLogin">Connexion</h1>

 <form action="{{ path("login") }}" method="post" id="formClient" >
        {{ error | raw}}
        <div class="form-group" class="groupeLabel">
        <label for="_username" class="label">Votre Email</label>
            <input type="text" class="form-control" placeholder="Adresse email...." require 
            name="_username" placeholder='Votre Email....'>
        
        </div>
            <div class="form-group">
                <label for="_password" class="label">Votre mot de passe</label>
                <input type="password" class="form-control" placeholder="Mot de passe...." require 
                name="_password" placeholder='Votre mot de passe....'>
            </div>

            <input type="hidden" name="_csrf_token"
            value="{{ csrf_token('authenticate') }}">

            <div class="form-group" class="groupeLabel">
                <button type="submit" class="btn btn-success" id="buttonForm">Connexion !</button>
            </div>
    </form>
</div>
{% endblock %}

templates/home_foodtruck/profil.html.twig
{% extends '/home_foodtruck/index.html.twig' %}

{% block body %}
{{ dump(user) }}
<div class="container">
    <div class="jumbotron" id='cadreForm' >
        <div class="form-group" id='formClient'>
            {{ form_start(form_foodtruck) }}
               {#  {{dump(form_foodtruck)}} #}
                    {{ form_row(form_foodtruck.username, {'label': 'Nom'}) }}
                  
                                {{ form_row(form_foodtruck.email,  {'label' : 'Email',
                                    'attr': {'placeholder': 'Votre Email...'}}) }}
                                {% if (user.nomEntreprise != 'Null') %}
                                    {{ form_row(form_foodtruck.nom_entreprise,  {'label' : 'Foodtruck'})}}
                                {% else %}
                                    {{ form_row(form_foodtruck.nom_entreprise,  {'attr' : {'style': 'display:none' }})}}
                                {% endif %}
                                        {{ form_row(form_foodtruck.tel,  {'label' : 'Tel'}) }}
                                            {{ form_row(form_foodtruck.ville,  {'label' : 'Ville'}) }}
                                            <button type="submit" class='btn btn-success btn-lg' id='buttonForm'>Mettre à jour</button>
                                                {{ form_rest(form_foodtruck) }}
                                                {{ form_end(form_foodtruck) }}

       </div>
    </div>
</div>
{% endblock  %}


{% block javascripts %}
<script src="/jquery.js"></script>
{% endblock %}